name: Build gem

on:
  push:
    branches:
      - '**'

jobs:
  build_gem:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1.81.0
        if: ${{ always() }}
        with:
          ruby-version: 'jruby-9.2.17.0'
          bundler-cache: true
      - name: Bundle Setup
        run: |
          gem install --no-document bundler
          bundle config path ${{ github.workspace }}/vendor/bundle
          rake jar
      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3
      - name: Set Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish to GitHub Packages
        run: |
          export OWNER=$( echo ${{ github.repository }} | cut -d "/" -f 1 )
          gem build activerecord-jdbc-adapter.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
